

import 'package:banana_deal_by_monkeycompany/package/common/edge/common_edge.dart';

abstract class CommonSize {
  const CommonSize();
  // Required base properties
  CommonEdge get edge;
  double get widthCommon;
  double get heightCommon;
  double get origin;

  // Height related
  double get staticMapSize;
  double get staticModalSize;
  double get height045;
  double get height05;
  double get height041;
  double get height001;
  double get height025;
  double get height1_2;
  double get etcH048;
  double get introCarousel;
  double get introImage;
  double get deviceMent;
  double get splashPad;

  // Sized related
  double get sizedSheet;
  double get sizedButtonNew;
  double get sizedButton;
  double get sizedAppbar;
  double get sizedNav;
  double get sizedNavWild;
  double get sizedDialogButton;
  double get sizedCategory;

  // Grid sizes
  double get sized32grid;
  double get sized24grid;
  double get sized20grid;
  double get sized16grid;
  double get sized12grid;
  double get sized8grid;
  double get sized6grid;
  double get sized4grid;
  double get sized2grid;

  // Padding sizes
  double get sizedPadding2;
  double get sizedPaddingQ;
  double get sizedPaddingW;
  double get sizedPaddingHalf;
  double get sizedPaddingHalfDouble;
  double get sizedPaddingOnlyAppBar;
  double get sizedSideGap;

  // Title sizes
  double get titleName;
  double get titleMain;
  double get titleButton;
  double get titleLittle;
  double get titleLarge;
  double get title27;

  // Text sizes
  double get body;
  double get callout;
  double get sub;
  double get special;
  double get foot;
  double get caption;

  // Theme
  double get extendsGap;
  double get sign2RowGap;

  // Width related
  double get widthChatCili;
  double get widthDec;
  double get widthCommon9_16;
  double get width01;
  double get width012;
  double get width016;
  double get width02;
  double get width03;
  double get width038;
  double get width0307;
  double get width001;
  double get width00234;
  double get width0021;
  double get width0017;
  double get width002;
  double get width005;
  double get width007;
  double get width0007;
  double get width0001;
  double get width00025;
  double get width003;
  double get width0038;
  double get width004;
  double get width0045;
  double get width0064;
  double get width0065;
  double get width00655;
  double get width0221;
  double get width0291;
  double get width024;
  double get width027;
  double get width06;
  double get width09;
  double get width0921;
  double get width0925;
  double get width057;

  // Heights
  double get height60px;
  double get height60px3n1;
  double get dialogCircular;
  double get dialogString;
  double get imageHeight;
  double get ratio58;
  double get ratio58_2;
  double get ratio58_33;
  double get ratio58_4;
  double get ratio58_3;
  double get ratioWidth;
  double get ratioHeight;
  double get imageWidth;
  double get srcFloatingActionBarSize;
  double get bannerWidth;
  double get permissionGap;
  double get characterSize;
  double get chatBoxPadding;

  // Sized boxes
  double get sizedBox0_5;
  double get sizedBox0_7;
  double get sizedBox1;
  double get sizedBox1_5;
  double get sizedBox2;
  double get sizedBox2_5;
  double get sizedBox3;
  double get sizedBox3_5;
  double get sizedBox4;
  double get sizedBox5;
  double get sizedBox6;
  double get sizedBox6_5;
  double get sizedBox7_5;
  double get sizedBox8;
  double get sizedBox9;
  double get sizedBox9_5;
  double get sizedBox10;
  double get sizedBox10_5;
  double get sizedBox11;
  double get sizedBox12;
  double get sizedBox13;
  double get sizedBox14;
  double get sizedBox15;
  double get sizedBox15_5;
  double get sizedBox16;
  double get sizedBox17;
  double get sizedBox18;
  double get sizedBox19;
  double get sizedBox20;
  double get sizedBox21;
  double get sizedBox22;
  double get sizedBox24;
  double get sizedBox25;
  double get sizedBox26;
  double get sizedBox28;
  double get sizedBox30;
  double get sizedBox32;
  double get sizedBox34;
  double get sizedBox35;
  double get sizedBox37;
  double get sizedBox39;
  double get sizedBox40;
  double get sizedBox42;
  double get sizedBox45;
  double get sizedBox48;
  double get sizedBox50;
  double get sizedSide1;
  double get sizedBox57;
  double get sizedBox585;
  double get sizedBox62;
  double get sizedBox65;
  double get sizedBox70;
  double get sizedBox72;
  double get sizedBox75;
  double get sizedBox77;
  double get sizedBox80;
  double get sizedBox84;
  double get sizedBox87_5;
  double get sizedBox88;
  double get sizedBox96;
  double get sizedBox100;
  double get sizedBox110;
  double get sizedBox114;
  double get sizedBox119;
  double get sizedBox119_2;
  double get sizedBox120;
  double get sizedBox121;
  double get sizedBox126;
  double get sizedBox128;
  double get sizedBox134;
  double get sizedBox136;
  double get sizedBox144;
  double get sizedBox148;
  double get sizedBox150;
  double get sizedBox151;
  double get sizedBox162;
  double get sizedBox165;
  double get sizedBox170;
  double get sizedBox181_5;
  double get sizedBox181;
  double get sizedBox182;
  double get sizedBox190;
  double get sizedBox200;
  double get sizedBox220;
  double get sizedBox220_5;
  double get sizedBox222;
  double get sizedBox225;

  // ETC sizes
  double get etcTitleSize;
  double get etcTimeGap;
  double get etcTimeSize;
  double get etcContentSize;
  double get sign2w1;
  double get sign2w2;
  double get listBox;
  double get sign2authE;
  double get sign2authE2;
  double get sizedBox0_1;
  double get sizedBox0_6;
  double get sizedBox0_62;
  double get sizedBox0_68;
  double get sizedBox1_4;
  double get etcList;
  double get chatMaxWidth065;
  double get chatMaxWidth075;
  double get textFromWidth;
  double get etc01;
  double get etc012;
  double get etc005;
  double get etc08;
  double get etc01325;
  double get etc0135;
  double get etc0156;
  double get etc041;
  double get reviewDialog;
  double get dealPad;
  double get etcStep;
  double get etcPad;
}