name: data_repository_provider
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0
  flutter_bloc: ^9.0.0

  redirect_repository:
    path: ../redirect_repository
  data_provider:
    path: ../../data/data_provider


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
