// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpOOY_NHCPy9pSABN_u2dPwlvEAIQTqRA',
    appId: '1:168957135631:android:2f7682713021506e810c7a',
    messagingSenderId: '168957135631',
    projectId: 'monkeysphone-dda5f',
    databaseURL: 'https://monkeysphone-dda5f.firebaseio.com',
    storageBucket: 'monkeysphone-dda5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Jnm5GLnHNiL63XDp1rpgcIvhDa2n9lE',
    appId: '1:168957135631:ios:88b0767563976f8d810c7a',
    messagingSenderId: '168957135631',
    projectId: 'monkeysphone-dda5f',
    databaseURL: 'https://monkeysphone-dda5f.firebaseio.com',
    storageBucket: 'monkeysphone-dda5f.appspot.com',
    androidClientId: '168957135631-9taqfoe2hjarsbc8e7hp103m56t2hv5q.apps.googleusercontent.com',
    iosClientId: '168957135631-mhho0qvvjb26rfd4ki1jtne6upavqhk5.apps.googleusercontent.com',
    iosBundleId: 'com.monkeycompany.bananadeal.bananaDealByMonkeycompany',
  );
}
