name: core
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  hive_ce_flutter: ^2.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  device_info_plus: ^11.2.1

  utils:
    path: ../utils

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
