name: css
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


flutter:
  assets:
    - assets/fonts/Pretendard-Bold.otf
    - assets/fonts/Pretendard-SemiBold.otf
    - assets/fonts/Pretendard-Medium.otf
    - assets/fonts/Pretendard-Regular.otf
    - assets/fonts/Pretendard-Light.otf
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300